#ifndef CONSTANTS_H_
#define CONSTANTS_H_

#define SCREEN_HEIGHT 600
#define SCREEN_WIDTH 600
#define SCREEN_AREA CLITERAL(Rectangle){0, 0, SCREEN_WIDTH, SCREEN_HEIGHT}
#define SCREEN_CENTER CLITERAL(Vector2) {SCREEN_WIDTH / 2, SCREEN_HEIGHT / 2}
#define NEARBLACK CLITERAL(Color) {15, 15, 15, 255}
#define FONT_SIZE 48

#define MAX_ASTROIDS 64
#define ASTROID_RANDOM_ANGLE 20 * DEG2RAD
#define ASTROID_DELAY 1.75f

#endif